name: CI/CD Workflow

on:
    push:
        branches:
            - "**"

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Actions
              uses: actions/checkout@v3

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Fmt
              run: deno fmt --check src

            - name: Lint
              run: deno lint src

            - name: Test
              run: |
                  deno test -A --parallel --doc --coverage=./coverage **/*.test.ts

            - name: Generate coverage report
              run: deno coverage --lcov ./coverage > coverage.lcov

            - name: Upload coverage report
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: ./coverage.lcov

    publish:
        if: github.ref == 'refs/heads/master'
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Publish package
              run: npx jsr publish
